### ISSUE TITLE
MonoGame Permission to use this Library

### ISSUE THREAD

**Issue by dellis1972** [bosoni/XNAnimationMG#1]
hi @bosoni 

I work on the MonoGame Framework. We are looking at expanding our 3D model and Animation support. I was wondering if it would would ok to fold this library into the core of MonoGame? We will of course abide by the License and full credit will be given. 

Thanks

**Comment by bosoni** [comment]
Of course :)

Dont remember did I change original XNAnimation (too bad codeplex isnt available any more), maybe I just created new solution and project file 7years ago.

**Comment by bosoni** [comment]
I didnt make original XNAnimation, I just make it work with Monogame long time ago. Maybe there is in some file original author which should be credited.

Ah just found original author: http://www.brunoevangelista.com/projects/

But with license, do what you want :)
